// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GenerateID(ctx context.Context, arg *GenerateIDParams) (int64, error)
	GetFullUrl(ctx context.Context, shortUrl pgtype.Text) (pgtype.Text, error)
	SetUrl(ctx context.Context, arg *SetUrlParams) error
}

var _ Querier = (*Queries)(nil)
