services:
  url-shortener:
    build: .
    image: "url_shortener_service"
    ports:
      - "8080:8080"
    depends_on:
      postgres-url-shortener-shard-1:
        condition: service_healthy

  postgres-url-shortener-shard-1:
    image: postgres:16
    environment:
      POSTGRES_DB: url_shortener_db
      POSTGRES_USER: url_shortener-user-1
      POSTGRES_PASSWORD: url_shortener-password-1
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U url_shortener-user-1 -d url_shortener_db" ]
      interval: 5s
      retries: 5
      timeout: 3s
